### ISSUE TITLE
Handlungsfeld "Handel, Innenstadt und Tourismus"

### ISSUE THREAD

**Issue by AndreasTraut** [stadtulm/smart-city-strategie#3]
Bisher sehe ich im Kapitel ["03_Handlungsfelder"](https://github.com/stadtulm/smart-city-strategie/tree/main/03_Handlungsfelder) nur das Handlungsfeld "Mobilität". Sind die anderen [11 Handlungsfelder](https://github.com/stadtulm/smart-city-strategie#was-kommt-in-die-strategie) noch nicht diskutiert worden? 

Ich sehe Ulm als eine Handelsstadt: vor Kurzem wurden in Ulm die [Sedelhöfe](https://www.sedelhöfe.com/) am Bahnhof [eröffnet](https://www.swp.de/suedwesten/staedte/ulm/sedelhoefe-ulm-eroeffnung-einweihung-hauptbahnhof-untefuehrung-tiefgarage-dc-developments-edeka-dm-snipes-mcdonalds-five-guys-zalando-ob-czisch-47801130.html). Viele weitere Beispiele zeigen, das "Handel" für Ulm wichtig ist. Daher scheint mir, dass aus dem [Best Practice Dokument](https://raw.githubusercontent.com/stadtulm/smart-city-strategie/main/00_Hintergrundmaterialien/Bericht_BestPractice_UrbanCatalyst.pdf) das Beispiel "Handel im Wandel" (Seite 22) sowie die dort genannten [weiterführenden Infos ](https://t1p.de/jiqy) für Ulm von Nutzen sein könnten. 

Ich würde gerne vorschlagen, das Handlungsfeld **"Handel, Innenstadt und Tourismus"** in das Kapiel ["03_Handlungsfelder"](https://github.com/stadtulm/smart-city-strategie/tree/main/03_Handlungsfelder) aufzunehmen, das genannte Beispiel auf Ulm zu adaptieren und dort im Detail zu diskutieren.

**Comment by NadjaWenger** [comment]
Danke für die Anregungen - wir nehmen die Links für die Formulierung des Kapitels mit! 

Die anderen 11 Handlungsfelder abgesehen von Mobilität sind vom Schreibprozess her noch nicht so weit, kommen aber! Die Verzögerungen sind übrigens auch im ReadMe in einem neuen Zeitplan abgebildet :)
